// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoIyzRy66w7VwTMmKgIm0RpFkNaPxfAIo',
    appId: '1:527845477946:web:be34f2ecf225dd0526ef03',
    messagingSenderId: '527845477946',
    projectId: 'flutter-project1-gsg',
    authDomain: 'flutter-project1-gsg.firebaseapp.com',
    storageBucket: 'flutter-project1-gsg.firebasestorage.app',
    measurementId: 'G-HLV9RDD6P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1jmASjfDRtIOidIBCSHyH7ha4TNpvhoc',
    appId: '1:527845477946:android:8d502b6deea842a926ef03',
    messagingSenderId: '527845477946',
    projectId: 'flutter-project1-gsg',
    storageBucket: 'flutter-project1-gsg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUkxTF0X1Z7EWtMu3-W0ChrXCja59E_D4',
    appId: '1:527845477946:ios:9389a49af98cf2d126ef03',
    messagingSenderId: '527845477946',
    projectId: 'flutter-project1-gsg',
    storageBucket: 'flutter-project1-gsg.firebasestorage.app',
    iosBundleId: 'com.example.recipeBookApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUkxTF0X1Z7EWtMu3-W0ChrXCja59E_D4',
    appId: '1:527845477946:ios:9389a49af98cf2d126ef03',
    messagingSenderId: '527845477946',
    projectId: 'flutter-project1-gsg',
    storageBucket: 'flutter-project1-gsg.firebasestorage.app',
    iosBundleId: 'com.example.recipeBookApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoIyzRy66w7VwTMmKgIm0RpFkNaPxfAIo',
    appId: '1:527845477946:web:836aadc64f7a9cd226ef03',
    messagingSenderId: '527845477946',
    projectId: 'flutter-project1-gsg',
    authDomain: 'flutter-project1-gsg.firebaseapp.com',
    storageBucket: 'flutter-project1-gsg.firebasestorage.app',
    measurementId: 'G-KSMVWS5YBR',
  );
}
